# Generated by Django 5.1.5 on 2025-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="period_no",
            field=models.CharField(default=1, max_length=10),
        ),
    ]
