# Generated by Django 5.1.5 on 2025-01-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0002_period_period_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("theoretical", "Theoretical"), ("sessional", "Sessional")],
                default="theoretical",
                max_length=15,
            ),
        ),
    ]
