# Generated by Django 5.1.5 on 2025-01-21 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0004_course_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="year",
        ),
    ]
