# Generated by Django 5.1.5 on 2025-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0005_remove_course_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="contact",
            field=models.CharField(
                blank=True, default="not provided", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="email",
            field=models.EmailField(
                blank=True,
                default="not provided",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
