# Generated by Django 5.1.5 on 2025-01-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine", "0007_alter_faculty_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="short_name",
            field=models.CharField(max_length=50),
        ),
    ]
